name: tests

on:
  push:
    branches: [ main, test ]   # run for both
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  # NEW: upgrade pip to the latest wheel-aware version
  - run: python -m pip install --upgrade pip

  - run: pip install -r requirements.txt

  - run: pytest -q
